FROM alpine:3.18.12@sha256:de0eb0b3f2a47ba1eb89389859a9bd88b28e82f5826b6969ad604979713c2d4f AS build

WORKDIR /workspace/program/gcta

RUN apk update && apk add \
        boost-dev \
        clang \
        clang-extra-tools \
        cmake \
        g++ \
        gcc \
        gfortran \
        gsl-dev \
        make \
        perl \
        sqlite-dev \
        wget \
        zlib-dev \
        zstd-dev

ADD https://github.com/OpenMathLib/OpenBLAS.git#v0.3.15 ./dependencies/openblas

RUN cd dependencies/openblas \
        && make \
        && make install PREFIX="/usr/include/openblas"

ADD https://gitlab.com/libeigen/eigen.git#3.3.7 ./dependencies/eigen

RUN cd dependencies/eigen \
        && mkdir -p build \
        && cd build \
        && cmake ../ -DBLAS_DIR="/usr/include/openblas" \
        && make install

ADD https://github.com/yixuan/spectra.git#v1.1.0 ./dependencies/spectra

RUN cd dependencies/spectra \
        && mkdir -p build \
        && cd build \
        && cmake -DCMAKE_INSTALL_PREFIX="/usr/include/spectra" -DCMAKE_PREFIX_PATH="/usr/local/include/eigen3" ../ \
        && make install

ADD https://github.com/jianyangqt/gcta.git#v1.94.1 ./codebase

ENV BOOST_LIB="/usr/include/boost/include" \
        EIGEN3_INCLUDE_DIR="/usr/local/include/eigen3" \
        OPENBLAS="/usr/include/openblas" \
        SPECTRA_LIB="/usr/include/spectra/include"

RUN cd codebase \
        && mkdir -p build \
        && cd build \
        && cmake ../ \
        && make \
        && cp gcta64 /usr/bin \
        && ln -s /usr/bin/gcta64 /usr/bin/gcta

RUN mkdir -p gcta-sharedlibs/apk-installed-libs gcta-sharedlibs/custom-built-libs gcta-executables \
        && cp -a /usr/lib/libsqlite3.so.0* \
        /usr/lib/libzstd.so.1* \
        /usr/lib/libgsl.so.27* \
        /usr/lib/libgslcblas.so.0* \
        /usr/lib/libgomp.so.1* \
        /usr/lib/libgfortran.so.5* \
        /usr/lib/libgcc_s.so.1 \
        gcta-sharedlibs/apk-installed-libs/ \
        && cp -a /usr/include/openblas/lib/libopenblas.so.0 \
        /usr/include/openblas/lib/libopenblas_armv8p-r0.3.15.so \
        gcta-sharedlibs/custom-built-libs/ \
        && cp -a /usr/bin/gcta* gcta-executables/

FROM alpine:3.18.12@sha256:de0eb0b3f2a47ba1eb89389859a9bd88b28e82f5826b6969ad604979713c2d4f AS production

COPY --from=build /workspace/program/gcta/gcta-sharedlibs/apk-installed-libs/ \
        /usr/lib/

COPY --from=build /workspace/program/gcta/gcta-sharedlibs/custom-built-libs/ \
        /usr/include/openblas/lib/

COPY --from=build /workspace/program/gcta/gcta-executables/ \
        /usr/bin/

WORKDIR /workspace/program/gcta/production
